// src/services/actions/types.ts
export const LOAD_INGREDIENTS_SUCCESS = 'LOAD_INGREDIENTS_SUCCESS'
export const LOAD_INGREDIENTS_FAILURE = 'LOAD_INGREDIENTS_FAILURE'
export const LOAD_INGREDIENTS_REQUEST = 'LOAD_INGREDIENTS_REQUEST'

export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT'
export const RESET_CURRENT_INGREDIENT  = 'RESET_CURRENT_INGREDIENT '

export const ADD_CONSTRUCTOR_INGREDIENT = 'ADD_CONSTRUCTOR_INGREDIENT'
export const REMOVE_CONSTRUCTOR_INGREDIENT = 'REMOVE_CONSTRUCTOR_INGREDIENT'
export const REPLACE_CONSTRUCTOR_BUNS = 'REPLACE_CONSTRUCTOR_BUNS'
export const SORT_CONSTRUCTOR_INGREDIENTS = 'SORT_CONSTRUCTOR_INGREDIENTS'

export const LOAD_ORDER_DETAILS_REQUEST = 'LOAD_ORDER_DETAILS_REQUEST'
export const LOAD_ORDER_DETAILS_SUCCESS = 'LOAD_ORDER_DETAILS_SUCCESS'
export const LOAD_ORDER_DETAILS_FAILURE = 'LOAD_ORDER_DETAILS_FAILURE'

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const CLEAR_ERROR = 'CLEAR_ERROR';
//export const TOKEN_REFRESH_FAILURE = 'TOKEN_REFRESH_FAILURE';