// src/services/actions/types.ts
export const LOAD_INGREDIENTS_SUCCESS = 'LOAD_INGREDIENTS_SUCCESS'
export const LOAD_INGREDIENTS_FAILURE = 'LOAD_INGREDIENTS_FAILURE'
export const LOAD_INGREDIENTS_REQUEST = 'LOAD_INGREDIENTS_REQUEST'

export const SET_CURRENT_INGREDIENT = 'SET_CURRENT_INGREDIENT'
export const RESET_CURRENT_INGREDIENT  = 'RESET_CURRENT_INGREDIENT '

export const ADD_CONSTRUCTOR_INGREDIENT = 'ADD_CONSTRUCTOR_INGREDIENT'
export const REMOVE_CONSTRUCTOR_INGREDIENT = 'REMOVE_CONSTRUCTOR_INGREDIENT'
export const REPLACE_CONSTRUCTOR_BUNS = 'REPLACE_CONSTRUCTOR_BUNS'
export const SORT_CONSTRUCTOR_INGREDIENTS = 'SORT_CONSTRUCTOR_INGREDIENTS'

export const LOAD_ORDER_DETAILS_REQUEST = 'LOAD_ORDER_DETAILS_REQUEST'
export const LOAD_ORDER_DETAILS_SUCCESS = 'LOAD_ORDER_DETAILS_SUCCESS'
export const LOAD_ORDER_DETAILS_FAILURE = 'LOAD_ORDER_DETAILS_FAILURE'